services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: prodmate
      POSTGRES_PASSWORD: prodmate
      POSTGRES_DB: prodmate
    ports:
      - "5432:5432"
    volumes:
      - prodmate_pg:/var/lib/postgresql/data

volumes:
  prodmate_pg:
